// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.DependencyRegistry
{
    [DbContext(typeof(DependencyRegistryDbContext))]
    partial class DependencyRegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.DependencyConfigurationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Key");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
