<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>true</IsPackable>
	<Version>1.0.0</Version>
	<Description>BPMN 2.0 Metamodel for .NET 9</Description>
	<AssemblyName>VertexBPMN.Model.Domain.Model.Grok</AssemblyName>
	<RootNamespace>VertexBPMN.Domain.Model</RootNamespace>
	  <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
	  <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	  <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MartinCostello.Logging.XUnit.v3" Version="0.6.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="xunit.v3" Version="3.0.1" />
		<PackageReference Include="Microsoft.Testing.Platform" Version="1.8.4" />
		<PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="1.8.4" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
		<PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Shouldly" Version="4.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\..\tests\VertexBPMN.Tests\TestData\**\*.*">
			<Link>TestData\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Schemas\BPMN20\BPMN20-FromXMI.xslt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\BPMN20.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\BPMNDI.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\DC.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\DI.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\Semantic.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>