<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>true</IsPackable>
	<Version>1.0.0</Version>
	<Description>BPMN 2.0 Metamodel for .NET 9</Description>
	<AssemblyName>VertexBPMN.Model.Domain.Model.Grok</AssemblyName>
	<RootNamespace>VertexBPMN.Domain.Model</RootNamespace>
	   <!--Disable caching to prevent infinite regeneration--> 
	  <!--<SourceGeneratorsCacheEnabled>false</SourceGeneratorsCacheEnabled>
	  <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	  <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>-->
  </PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="Cmmn\**" />
	  <EmbeddedResource Remove="Cmmn\**" />
	  <None Remove="Cmmn\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Schemas\BPMN20\BPMN20-FromXMI.xslt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\BPMN20.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\BPMNDI.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\DC.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\DI.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Schemas\BPMN20\Semantic.xsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.30" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
		<PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\utils\VertexBPMN.EntityGenerator\VertexBPMN.EntityGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>