apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexbpmn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vertexbpmn
  template:
    metadata:
      labels:
        app: vertexbpmn
    spec:
      containers:
      - name: vertexbpmn
        image: vertexbpmn:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__ProcessMiningEvents
          value: "Host=postgres;Port=5432;Database=vertexbpmn_events;Username=vertexbpmn;Password=vertexbpmn"
---
apiVersion: v1
kind: Service
metadata:
  name: vertexbpmn
spec:
  type: ClusterIP
  selector:
    app: vertexbpmn
  ports:
  - port: 80
    targetPort: 80
