// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence.Services;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.Simulation
{
    [DbContext(typeof(SimulationScenarioDbContext))]
    partial class SimulationScenarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("VertexBPMN.Domain.Entities.SimulationScenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BpmnXml")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxSteps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "sim-sample-1",
                            Description = "Ein einfacher Simulationstest",
                            MaxSteps = 100,
                            Name = "Throughput Test",
                            ProcessDefinitionId = "22222222-2222-2222-2222-222222222222",
                            TenantId = "tenant-default"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
