// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence;
using VertexBPMN.Persistence.Migrations;

#nullable disable

namespace VertexBPMN.Persistence.Migrations
{
    [DbContext(typeof(BpmnDbContext))]
    partial class BpmnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VertexBPMN.Domain.Entities.EngineDeployment", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Name").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("TenantId");
                b.HasIndex("Name");
                b.HasIndex("Name","TenantId");
                b.ToTable("EngineDeployments");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessDefinition", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("Key").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Name").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<int>("Version").HasColumnType("INTEGER");
                b.Property<string>("BpmnXml").HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<Guid>("DeploymentId").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Key");
                b.HasIndex("Key","Version").IsUnique();
                b.HasIndex("TenantId");
                b.HasIndex("DeploymentId");
                b.ToTable("ProcessDefinitions");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessInstance", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessDefinitionId").HasColumnType("TEXT");
                b.Property<string>("BusinessKey").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<DateTime>("StartedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("EndedAt").HasColumnType("TEXT");
                b.Property<string>("State").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("InstanceId").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("ProcessId").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<string>("ActiveTasks").HasColumnType("TEXT");
                b.Property<string>("ActiveTokens").HasColumnType("TEXT");
                b.Property<string>("Variables").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime>("LastModified").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessDefinitionId");
                b.HasIndex("BusinessKey");
                b.HasIndex("TenantId");
                b.HasIndex("State");
                b.HasIndex("StartedAt");
                b.ToTable("ProcessInstances");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ExecutionToken", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("CurrentNodeId").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("NodeType").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Variables").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("AssignedWorker").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<DateTime?>("AssignedAt").HasColumnType("TEXT");
                b.Property<int>("RetryCount").HasColumnType("INTEGER");
                b.Property<string>("State").HasMaxLength(50).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("CurrentNodeId");
                b.HasIndex("State");
                b.HasIndex("AssignedWorker");
                b.HasIndex("CreatedAt");
                b.ToTable("ExecutionTokens");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Variable", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ScopeId").HasColumnType("TEXT");
                b.Property<string>("Name").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Type").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Value").HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ScopeId");
                b.HasIndex("Name");
                b.HasIndex("Type");
                b.HasIndex("TenantId");
                b.HasIndex("ProcessInstanceId");
                b.ToTable("Variables");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Job", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("Type").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("DueDate").HasColumnType("TEXT");
                b.Property<int>("Retries").HasColumnType("INTEGER");
                b.Property<string>("ErrorMessage").HasMaxLength(4000).HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("State").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("Payload").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("Type");
                b.HasIndex("State");
                b.HasIndex("DueDate");
                b.HasIndex("TenantId");
                b.ToTable("Jobs");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.UserTask", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("Name").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Type").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Assignee").HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("DueDate").HasColumnType("TEXT");
                b.Property<string>("FormKey").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("FormSchema").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("Type");
                b.HasIndex("TenantId");
                b.HasIndex("Assignee");
                b.ToTable("Tasks");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.HistoryEvent", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("EventType").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("Timestamp").HasColumnType("TEXT");
                b.Property<string>("Details").HasMaxLength(4000).HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("ElementId").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Data").HasMaxLength(4000).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("EventType");
                b.HasIndex("ElementId");
                b.HasIndex("Timestamp");
                b.HasIndex("TenantId");
                b.ToTable("HistoryEvents");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Incident", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("Type").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Message").HasMaxLength(4000).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("State").HasMaxLength(50).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("Type");
                b.HasIndex("State");
                b.HasIndex("CreatedAt");
                b.HasIndex("TenantId");
                b.ToTable("Incidents");
            });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.MultiInstanceExecution", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<Guid>("ProcessInstanceId").HasColumnType("TEXT");
                b.Property<string>("ActivityId").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<int>("InstanceCount").HasColumnType("INTEGER");
                b.Property<int>("CompletedCount").HasColumnType("INTEGER");
                b.Property<bool>("IsSequential").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("ActivityId");
                b.HasIndex("ProcessInstanceId","ActivityId");
                b.ToTable("MultiInstanceExecutions");
            });
#pragma warning restore 612, 618
        }
    }
}
