//using System.Linq;
//using Microsoft.CodeAnalysis;
//using Microsoft.CodeAnalysis.CSharp;
//using Microsoft.CodeAnalysis.CSharp.Syntax;
//using Microsoft.CodeAnalysis.Text;
//using System;
//using System.Collections.Generic;
//using System.Collections.Immutable;
//using System.Linq;
//using System.Text;

//namespace VertexBPMN.EntityGenerator;

//[Generator]
//public class EntityFromModelGenerator : IIncrementalGenerator
//{
//    public void Initialize(IncrementalGeneratorInitializationContext context)
//    {
//        // Raw model classes (un-distinct)
//        var rawModelClasses = context.SyntaxProvider
//            .CreateSyntaxProvider(
//                predicate: (node, ct) =>
//                    node is ClassDeclarationSyntax cds
//                    && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword))
//                    && cds.Parent is NamespaceDeclarationSyntax,
//                transform: (ctx, ct) =>
//                {
//                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
//                    var semantic = ctx.SemanticModel;
//                    var symbol = semantic.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
//                    if (symbol == null)
//                        return null;

//                    if (symbol.TypeKind != TypeKind.Class || symbol.IsAbstract)
//                        return null;

//                    var ns = symbol.ContainingNamespace?.ToDisplayString();
//                    if (ns == null || !ns.StartsWith("VertexBPMN.Domain.Model.Bpmn"))
//                        return null;

//                    return symbol;
//                })
//            .Where(sym => sym is not null)
//            .Select((sym, ct) => sym!);

//        // Distinct set (ImmutableArray)
//        var distinctModelsProvider = rawModelClasses
//            .Collect()
//            .Select((models, _) => models
//                .Distinct(SymbolEqualityComparer.Default)
//                .ToImmutableArray());

//        // Per-entity generation (flatten immutable array)
//        context.RegisterSourceOutput(
//            distinctModelsProvider.SelectMany((models, _) => models),
//            (spc, symbol) =>
//            {
//                if (symbol is INamedTypeSymbol namedTypeSymbol)
//                {
//                    GenerateEntity(spc, namedTypeSymbol);
//                    // EF-Konfigurationen werden in BpmnDbContext als Methoden generiert (nicht separat).
//                }
//            });

//        // DbContext generation (use distinct symbols directly)
//        context.RegisterSourceOutput(distinctModelsProvider, (spc, symbols) =>
//        {
//            var namedTypeSymbols = symbols.OfType<INamedTypeSymbol>().ToList();
//            GenerateDbContext(spc, namedTypeSymbols.ToList());
//        });
//    }

//    private void GenerateEntity(SourceProductionContext spc, INamedTypeSymbol symbol)
//    {
//        var originalNs = symbol.ContainingNamespace.ToDisplayString();
//        var entityNs = originalNs.Replace("VertexBPMN.Domain.Model.Bpmn", "VertexBPMN.Domain.Model.Bpmn.Entities");
//        var className = symbol.Name;
//        var entityName = className + "Entity";

//        var sb = new StringBuilder();
//        sb.AppendLine("// <auto-generated />");
//        sb.AppendLine("using System;");
//        sb.AppendLine("using System.Collections.Generic;");
//        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
//        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
//        sb.AppendLine();
//        sb.AppendLine($"namespace {entityNs}");
//        sb.AppendLine("{");
//        sb.AppendLine($"    public partial class {entityName}");
//        sb.AppendLine("    {");

//        // 1) Prüfe, ob Id bereits vorhanden ist
//        bool hasId = GetAllProperties(symbol)
//            .Any(p => p.Name == "Id" || p.GetAttributes().Any(a => a.AttributeClass?.Name == "KeyAttribute"));
//        if (!hasId)
//        {
//            sb.AppendLine("        [Key]");
//            sb.AppendLine("        public Guid Id { get; set; }");
//        }

//        // 2) Alle Eigenschaften (inklusive Basisklassen) verarbeiten
//        foreach (var prop in GetAllProperties(symbol))
//        {
//            if (prop.DeclaredAccessibility != Accessibility.Public || prop.IsStatic)
//                continue;

//            if (prop.Name == "Id")
//                continue;

//            var propType = prop.Type as INamedTypeSymbol;
//            var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

//            // XmlQualifiedName -> string
//            if (typeName == "System.Xml.XmlQualifiedName" || typeName == "XmlQualifiedName")
//            {
//                sb.AppendLine($"        public string {prop.Name} {{ get; set; }} = string.Empty;");
//                continue;
//            }

//            // List<XmlQualifiedName> -> string
//            if (propType != null && propType.IsGenericType
//                && (propType.Name == "List" || propType.Name == "ICollection")
//                && propType.TypeArguments.Length == 1
//                && propType.TypeArguments[0].ToDisplayString() == "System.Xml.XmlQualifiedName")
//            {
//                sb.AppendLine($"        // Stored as JSON or comma-separated string for XmlQualifiedName list");
//                sb.AppendLine($"        public string {prop.Name} {{ get; set; }} = string.Empty;");
//                continue;
//            }

//            // List<XmlAttribute> -> Dictionary
//            if (propType != null && propType.IsGenericType
//                && (propType.Name == "List" || propType.Name == "IList" || propType.Name == "ICollection")
//                && propType.TypeArguments.Length == 1
//                && propType.TypeArguments[0].ToDisplayString() == "System.Xml.XmlAttribute")
//            {
//                sb.AppendLine($"        public Dictionary<string, object>? {prop.Name}Dictionary {{ get; set; }}");
//                continue;
//            }

//            // Many-Navigation: ICollection<T>/List<T> auf Bpmn-Namespace
//            if (propType != null && propType.IsGenericType
//                && (propType.Name == "ICollection" || propType.Name == "List")
//                && propType.TypeArguments.Length == 1)
//            {
//                var arg = propType.TypeArguments[0] as INamedTypeSymbol;
//                if (arg != null && arg.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true)
//                {
//                    var navEntity = arg.Name + "Entity";
//                    var pluralName = Pluralize(arg.Name);
//                    sb.AppendLine($"        public ICollection<{navEntity}> {pluralName} {{ get; set; }} = new List<{navEntity}>();");
//                    continue;
//                }
//            }

//            // Single-Navigation: Referenz auf andere Modellklasse
//            if (propType != null && propType.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true)
//            {
//                var navEntity = propType.Name + "Entity";
//                sb.AppendLine($"        [ForeignKey(nameof({prop.Name}))]");
//                sb.AppendLine($"        public Guid {prop.Name}Id {{ get; set; }}");
//                sb.AppendLine($"        public {navEntity} {prop.Name} {{ get; set; }} = null!;");
//                continue;
//            }

//            // Enum
//            if (propType != null && propType.TypeKind == TypeKind.Enum)
//            {
//                var enumTypeName = propType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
//                sb.AppendLine($"        public {enumTypeName} {prop.Name} {{ get; set; }}");
//                continue;
//            }

//            // Normale Eigenschaft
//            if (typeName == "string" && !prop.NullableAnnotation.HasFlag(NullableAnnotation.Annotated))
//            {
//                sb.AppendLine("        [Required, MaxLength(255)]");
//                sb.AppendLine($"        public {typeName} {prop.Name} {{ get; set; }} = string.Empty;");
//            }
//            else if (typeName == "string?")
//            {
//                sb.AppendLine("        [MaxLength(255)]");
//                sb.AppendLine($"        public {typeName} {prop.Name} {{ get; set; }}");
//            }
//            else
//            {
//                sb.AppendLine($"        public {typeName} {prop.Name} {{ get; set; }}");
//            }
//        }

//        sb.AppendLine("    }");
//        sb.AppendLine("}");
//        spc.AddSource($"{entityName}.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
//    }

//    private void GenerateDbContext(SourceProductionContext spc, List<INamedTypeSymbol> symbols)
//    {
//        var sb = new StringBuilder();
//        sb.AppendLine("// <auto-generated />");
//        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
//        sb.AppendLine();
//        sb.AppendLine("namespace VertexBPMN.Domain.Model.Bpmn.Entities");
//        sb.AppendLine("{");
//        sb.AppendLine("    public partial class BpmnDbContext : DbContext");
//        sb.AppendLine("    {");
//        sb.AppendLine("        public BpmnDbContext(DbContextOptions<BpmnDbContext> options) : base(options) { }");
//        sb.AppendLine();

//        // DbSets
//        foreach (var sym in symbols)
//        {
//            var entityName = sym.Name + "Entity";
//            var pluralName = Pluralize(sym.Name);
//            sb.AppendLine($"        public DbSet<{entityName}> {pluralName} {{ get; set; }} = null!;");
//        }

//        sb.AppendLine();
//        sb.AppendLine("        protected override void OnModelCreating(ModelBuilder modelBuilder)");
//        sb.AppendLine("        {");
//        sb.AppendLine("            base.OnModelCreating(modelBuilder);");
//        sb.AppendLine();

//        // Call per-entity methods
//        foreach (var sym in symbols)
//        {
//            var entityName = sym.Name + "Entity";
//            sb.AppendLine($"            Configure{entityName}(modelBuilder);");
//        }

//        sb.AppendLine("        }");
//        sb.AppendLine();

//        // Per-entity configure methods inside DbContext (mit Indizes, Relationen, Constraints)
//        foreach (var sym in symbols)
//        {
//            var entityName = sym.Name + "Entity";
//            var tableName = Pluralize(sym.Name);
//            var props = GetAllProperties(sym).Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic).ToList();

//            sb.AppendLine($"        private static void Configure{entityName}(ModelBuilder modelBuilder)");
//            sb.AppendLine("        {");
//            sb.AppendLine($"            var builder = modelBuilder.Entity<{entityName}>();");
//            sb.AppendLine($"            builder.ToTable(\"{tableName}\");");
//            sb.AppendLine("            builder.HasKey(e => e.Id);");

//            // Property-Konfigurationen (Strings, XmlQualifiedName -> string, Listen etc.)
//            foreach (var p in props)
//            {
//                var pType = p.Type as INamedTypeSymbol;
//                var typeName = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

//                // Überspringe Navigations-Properties (Originalmodell: werden unten als Relationen behandelt)
//                bool isModelNavSingle = pType != null
//                                        && pType.TypeKind == TypeKind.Class
//                                        && pType.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true;
//                bool isModelNavMany = pType != null
//                                      && pType.IsGenericType
//                                      && (pType.Name == "ICollection" || pType.Name == "List")
//                                      && pType.TypeArguments.Length == 1
//                                      && pType.TypeArguments[0] is INamedTypeSymbol argNav
//                                      && argNav.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true;

//                if (isModelNavSingle || isModelNavMany)
//                    continue;

//                // Name-Index (falls "Name" vorhanden)
//                if (p.Name == "Name" && (typeName == "string" || typeName == "string?"))
//                {
//                    sb.AppendLine($"            builder.HasIndex(e => e.Name).HasDatabaseName(\"IX_{entityName}_Name\");");
//                }

//                // String Required/Optional (entspr. Entitäts-Property existiert 1:1)
//                if (typeName == "string")
//                {
//                    sb.AppendLine($"            builder.Property(e => e.{p.Name})");
//                    sb.AppendLine("                   .HasMaxLength(255)");
//                    sb.AppendLine("                   .IsRequired();");
//                }
//                else if (typeName == "string?")
//                {
//                    sb.AppendLine($"            builder.Property(e => e.{p.Name})");
//                    sb.AppendLine("                   .HasMaxLength(255)");
//                    sb.AppendLine("                   .IsRequired(false);");
//                }

//                // XmlQualifiedName -> string (wir haben 1:1 übernommen, also ggf. größere Länge)
//                if (typeName == "System.Xml.XmlQualifiedName" || typeName == "XmlQualifiedName")
//                {
//                    // In der Entity wurde dafür eine string-Property gleichen Namens erzeugt
//                    sb.AppendLine($"            builder.Property(e => e.{p.Name})");
//                    sb.AppendLine("                   .HasMaxLength(512)");
//                    sb.AppendLine("                   .IsRequired(false);");
//                }

//                // List<XmlQualifiedName> -> string (nvarchar(max) sinnvoll)
//                if (pType != null && pType.IsGenericType
//                    && (pType.Name == "List" || pType.Name == "ICollection")
//                    && pType.TypeArguments.Length == 1
//                    && pType.TypeArguments[0].ToDisplayString() == "System.Xml.XmlQualifiedName")
//                {
//                    sb.AppendLine($"            builder.Property(e => e.{p.Name})");
//                    sb.AppendLine("                   .HasColumnType(\"nvarchar(max)\")");
//                    sb.AppendLine("                   .IsRequired(false);");
//                }

//                // List<XmlAttribute> -> Dictionary<string, object> (nicht Mapped ohne Konverter)
//                if (pType != null && pType.IsGenericType
//                    && (pType.Name == "List" || pType.Name == "IList" || pType.Name == "ICollection")
//                    && pType.TypeArguments.Length == 1
//                    && pType.TypeArguments[0].ToDisplayString() == "System.Xml.XmlAttribute")
//                {
//                    // Entitäts-Property heißt {OriginalName}Dictionary
//                    sb.AppendLine($"            builder.Ignore(e => e.{p.Name}Dictionary);");
//                }
//            }

//            // Relationen und FKs für Single-Navigationen (Originalmodell: prop vom Typ einer Bpmn-Klasse)
//            foreach (var p in props)
//            {
//                var pType = p.Type as INamedTypeSymbol;
//                bool isModelNavSingle = pType != null
//                                        && pType.TypeKind == TypeKind.Class
//                                        && pType.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true;

//                if (!isModelNavSingle) continue;

//                var navEntity = (pType!.Name) + "Entity";
//                var navPropName = p.Name;           // Navigation property in Entity
//                var fkPropName = p.Name + "Id";     // FK in Entity

//                // Index auf FK
//                sb.AppendLine($"            builder.HasIndex(e => e.{fkPropName}).HasDatabaseName(\"IX_{entityName}_{fkPropName}\");");

//                // Relation (Restrict als Default)
//                sb.AppendLine($"            builder.HasOne(e => e.{navPropName})");
//                sb.AppendLine("                   .WithMany()");
//                sb.AppendLine($"                   .HasForeignKey(e => e.{fkPropName})");
//                sb.AppendLine("                   .OnDelete(DeleteBehavior.Restrict);");
//            }

//            // Optionale Navigation-Konfiguration für Many-Seite (AutoInclude als Beispiel, wenn erstellt)
//            foreach (var p in props)
//            {
//                var pType = p.Type as INamedTypeSymbol;
//                bool isModelNavMany = pType != null
//                                      && pType.IsGenericType
//                                      && (pType.Name == "ICollection" || pType.Name == "List")
//                                      && pType.TypeArguments.Length == 1
//                                      && pType.TypeArguments[0] is INamedTypeSymbol argNav
//                                      && argNav.ContainingNamespace?.ToDisplayString().StartsWith("VertexBPMN.Domain.Model.Bpmn") == true;

//                if (!isModelNavMany) continue;

//                var arg = (INamedTypeSymbol)pType!.TypeArguments[0];
//                var pluralName = Pluralize(arg.Name); // So wurde die Entitäts-Navigation benannt
//                // Wir konfigurieren hier nur die Navigation (falls vorhanden). FK wird auf der anderen Seite verwaltet.
//                sb.AppendLine($"            builder.Navigation(e => e.{pluralName}).AutoInclude(false);");
//            }

//            sb.AppendLine("        }");
//            sb.AppendLine();
//        }

//        sb.AppendLine("    }");
//        sb.AppendLine("}");
//        spc.AddSource($"BpmnDbContext.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
//    }

//    private static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol symbol)
//    {
//        var props = new List<IPropertySymbol>();
//        INamedTypeSymbol? current = symbol;
//        while (current != null && current.SpecialType != SpecialType.System_Object)
//        {
//            props.AddRange(current.GetMembers().OfType<IPropertySymbol>());
//            current = current.BaseType;
//        }
//        return props.Distinct(SymbolEqualityComparer.Default).Cast<IPropertySymbol>();
//    }

//    private static string Pluralize(string name)
//    {
//        if (name.EndsWith("y", StringComparison.OrdinalIgnoreCase))
//            return name.Substring(0, name.Length - 1) + "ies";
//        if (name.EndsWith("s", StringComparison.OrdinalIgnoreCase)
//            || name.EndsWith("x", StringComparison.OrdinalIgnoreCase)
//            || name.EndsWith("z", StringComparison.OrdinalIgnoreCase)
//            || name.EndsWith("ch", StringComparison.OrdinalIgnoreCase)
//            || name.EndsWith("sh", StringComparison.OrdinalIgnoreCase))
//            return name + "es";
//        return name + "s";
//    }
//}