namespace VertexBPMN.EntityGenerator;

// <auto-generated>
// Generates FULL records (not just partials) with two constructors added:
// - Parameterless ctor (protected for abstract, public otherwise)
// - Parameterized ctor with all public settable properties (including inherited)
//   * List<T> properties use IEnumerable<T>? params and null -> empty list
//
// IMPORTANT: Exclude your original Bpmn2 source files during build to avoid duplicate type definitions
//            (see MSBuild tip in the assistant response).
// </auto-generated>

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;


[Generator]
public sealed class RecordConstructorsFullGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var records = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is RecordDeclarationSyntax r && r.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)),
                transform: static (ctx, _) =>
                {
                    var r = (RecordDeclarationSyntax)ctx.Node;
                    var sym = ctx.SemanticModel.GetDeclaredSymbol(r) as INamedTypeSymbol;
                    return sym;
                })
            .Where(s => s is not null)
            .Select((s, _) => s!) // INamedTypeSymbol
            .Collect();

        context.RegisterSourceOutput(records, (spc, symbols) =>
        {
            var targets = symbols
                .Where(s => s.ContainingNamespace?.ToDisplayString() == "VertexBPMN.Domain.Model.Bpmn2")
                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                .ToArray();

            foreach (INamedTypeSymbol type in targets)
            {
                try
                {
                    var src = GenerateFullRecordWithCtors(type);
                    var hint = $"{type.Name}.cs".Replace('<', '_').Replace('>', '_');
                    spc.AddSource(hint, SourceText.From(src, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    spc.AddSource($"{type.Name}.cs", SourceText.From($"// Generation failed for {type.ToDisplayString()}\n// {ex}", Encoding.UTF8));
                }
            }
        });
    }
    private static string GenerateFullRecordWithCtors(INamedTypeSymbol type)
    {
        var declRef = type.DeclaringSyntaxReferences.FirstOrDefault();
        if (declRef is null) return $"// No declaration for {type}";

        var syntax = (RecordDeclarationSyntax)declRef.GetSyntax();

        // 1) Detect if a parameterless ctor exists (explicit or implicit)
        // Implicit parameterless constructors appear in InstanceConstructors with IsImplicitlyDeclared == true
        bool hasDefaultCtor = type.InstanceConstructors.Any(ctor =>
            !ctor.IsStatic && ctor.Parameters.Length == 0);

        // 2) Rewrite existing ctors: change public -> protected
        var updatedMembers = new List<MemberDeclarationSyntax>();
        foreach (var member in syntax.Members)
        {
            if (member is ConstructorDeclarationSyntax ctor)
            {
                var newModifiers = ctor.Modifiers;

                // If ctor is explicitly public, change to protected
                if (ctor.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)))
                {
                    newModifiers = new SyntaxTokenList(
                        ctor.Modifiers.Select(m => m.IsKind(SyntaxKind.PublicKeyword)
                            ? SyntaxFactory.Token(SyntaxKind.ProtectedKeyword)
                            : m));
                }

                // If record is abstract, make all instance ctors protected (even if they weren't public)
                if (type.IsAbstract && !ctor.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
                {
                    // replace any visibility keyword with protected (if any visibility exists); otherwise prepend protected
                    if (newModifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword) ||
                                              m.IsKind(SyntaxKind.InternalKeyword) ||
                                              m.IsKind(SyntaxKind.PrivateKeyword) ||
                                              m.IsKind(SyntaxKind.ProtectedKeyword)))
                    {
                        newModifiers = new SyntaxTokenList(newModifiers.Select(m =>
                            (m.IsKind(SyntaxKind.PublicKeyword) || m.IsKind(SyntaxKind.InternalKeyword) ||
                             m.IsKind(SyntaxKind.PrivateKeyword))
                            ? SyntaxFactory.Token(SyntaxKind.ProtectedKeyword)
                            : m));
                    }
                    else
                    {
                        newModifiers = newModifiers.Insert(0, SyntaxFactory.Token(SyntaxKind.ProtectedKeyword));
                    }
                }

                updatedMembers.Add(ctor.WithModifiers(newModifiers));
            }
            else
            {
                updatedMembers.Add(member);
            }
        }

        var updatedRecord = syntax.WithMembers(SyntaxFactory.List(updatedMembers));

        // 3) Add parameterized constructor ONLY if a default ctor exists
        if (hasDefaultCtor)
        {
            var props = GetAllPublicSettableProperties(type).ToArray();
            if (props.Length > 0)
            {
                var vis = type.IsAbstract ? SyntaxKind.ProtectedKeyword : SyntaxKind.PublicKeyword;
                var paramCtor = SyntaxFactory.ConstructorDeclaration(type.Name)
                    .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(vis)))
                    .WithParameterList(BuildParameterList(props))
                    .WithBody(BuildAssignmentBody(props));

                // Ensure we don't already have an identical signature (best-effort: same parameter count)
                bool alreadyHasSimilar = updatedRecord.Members
                    .OfType<ConstructorDeclarationSyntax>()
                    .Any(c => c.ParameterList.Parameters.Count == props.Length);

                if (!alreadyHasSimilar)
                {
                    updatedRecord = updatedRecord.AddMembers(paramCtor);
                }
            }
        }

        // 4) Emit a full compilation unit that preserves attributes and base types
        var usings = new[]
        {
        "System",
        "System.Collections.Generic",
        "System.Linq",
        "System.Xml.Serialization",
        "System.ComponentModel",
        "System.Diagnostics"
    }.Select(u => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(u)));

        var ns = type.ContainingNamespace?.ToDisplayString() ?? "VertexBPMN.Domain.Model.Bpmn2";
        var cu = SyntaxFactory.CompilationUnit()
            .AddUsings(usings.ToArray())
            .AddMembers(SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(ns))
                .AddMembers(updatedRecord))
            .WithLeadingTrivia(SyntaxFactory.Comment("// <auto-generated/>"))
            .NormalizeWhitespace();

        return cu.ToFullString();
    }

    // helpers: same as before

    private static IEnumerable<IPropertySymbol> GetAllPublicSettableProperties(INamedTypeSymbol t)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var cur = t; cur != null && cur.SpecialType != SpecialType.System_Object; cur = cur.BaseType)
        {
            foreach (var p in cur.GetMembers().OfType<IPropertySymbol>())
            {
                if (p.IsStatic) continue;
                if (p.DeclaredAccessibility != Accessibility.Public) continue;
                if (p.SetMethod is null) continue;
                var key = $"{p.Name}|{p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}";
                if (seen.Add(key))
                    yield return p;
            }
        }
    }

    private static ParameterListSyntax BuildParameterList(IEnumerable<IPropertySymbol> props)
    {
        var parameters = props.Select(p =>
        {
            var type = GetParameterTypeText(p);
            var name = ToParamName(p.Name);
            return SyntaxFactory.Parameter(SyntaxFactory.Identifier(name))
                .WithType(SyntaxFactory.ParseTypeName(type));
        });
        return SyntaxFactory.ParameterList(SyntaxFactory.SeparatedList(parameters));
    }

    private static BlockSyntax BuildAssignmentBody(IEnumerable<IPropertySymbol> props)
    {
        var statements = props.Select(BuildAssignmentStatement).ToArray();
        return SyntaxFactory.Block(statements);
    }

    private static StatementSyntax BuildAssignmentStatement(IPropertySymbol p)
    {
        var propName = p.Name;
        var paramName = ToParamName(p.Name);
        var pType = p.Type as INamedTypeSymbol;

        if (pType is not null && IsListType(pType, out var elem))
        {
            var elemTypeText = elem.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            var stmt = $"this.{propName} = new List<{elemTypeText}>({paramName} ?? Enumerable.Empty<{elemTypeText}>());";
            return SyntaxFactory.ParseStatement(stmt);
        }
        return SyntaxFactory.ParseStatement($"this.{propName} = {paramName};");
    }

    private static bool IsListType(INamedTypeSymbol t, out ITypeSymbol elem)
    {
        elem = t;
        var isList =
            t.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.List<T>" ||
            t.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.ICollection<T>" ||
                                     i.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>");
        if (isList && t.TypeArguments.Length == 1)
        {
            elem = t.TypeArguments[0];
            return true;
        }
        return false;
    }

    private static string GetParameterTypeText(IPropertySymbol p)
    {
        if (p.Type is INamedTypeSymbol nt && IsListType(nt, out var elem))
        {
            var elemType = elem.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            return $"IEnumerable<{elemType}>?";
        }
        return p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
    }

    private static string ToParamName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "value";
        return name.Length == 1
            ? char.ToLowerInvariant(name[0]).ToString()
            : char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
