// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.Bpmn
{
    [DbContext(typeof(BpmnDbContext))]
    [Migration("20260811182524_AddIdentityTenantScope")]
    partial class AddIdentityTenantScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("VertexBPMN.Domain.Entities.EngineDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId");

                    b.ToTable("EngineDeployments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SampleDeployment"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ExecutionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AssignedAt");

                    b.Property<string>("AssignedWorker")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CurrentNodeId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("ProcessInstanceId");

                    b.Property<int>("RetryCount");

                    b.Property<string>("State")
                        .HasMaxLength(50);

                    b.Property<string>("Variables")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AssignedWorker");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentNodeId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("State");

                    b.ToTable("ExecutionTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentNodeId = "startEvent1",
                            NodeType = "startEvent",
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RetryCount = 0,
                            State = "Active",
                            Variables = "{}"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.HistoryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .HasMaxLength(4000);

                    b.Property<string>("Details")
                        .HasMaxLength(4000);

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("ProcessInstanceId");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("EventType");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoryEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Details = "Process instance started.",
                            ElementId = "startEvent1",
                            EventType = "PROCESS_STARTED",
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<Guid>("ProcessInstanceId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("State");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "No incident",
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            State = "Resolved",
                            Type = "None"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000);

                    b.Property<string>("Payload");

                    b.Property<Guid>("ProcessInstanceId");

                    b.Property<int>("Retries");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("State");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DueDate = new DateTime(2025, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Retries = 3,
                            State = "Scheduled",
                            Type = "timer"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.MigrationExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("MigrationPlanId");

                    b.Property<string>("Payload")
                        .IsRequired();

                    b.Property<DateTime>("StartedAt");

                    b.HasKey("Id");

                    b.HasIndex("MigrationPlanId");

                    b.HasIndex("StartedAt");

                    b.ToTable("MigrationExecutions");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.MigrationPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Payload")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("MigrationPlans");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.MultiInstanceExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("CompletedCount");

                    b.Property<int>("InstanceCount");

                    b.Property<bool>("IsSequential");

                    b.Property<Guid>("ProcessInstanceId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("ProcessInstanceId", "ActivityId");

                    b.ToTable("MultiInstanceExecutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ActivityId = "activity_multi_1",
                            CompletedCount = 0,
                            InstanceCount = 3,
                            IsSequential = true,
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BpmnXml")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("DeploymentId");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("Key");

                    b.HasIndex("TenantId");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BpmnXml = "<definitions id='SampleProcess'></definitions>",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeploymentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "SampleProcess",
                            Name = "Sample Process",
                            Version = 1
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveTasks")
                        .IsRequired();

                    b.Property<string>("ActiveTokens")
                        .IsRequired();

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("EndedAt");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModified");

                    b.Property<Guid>("ProcessDefinitionId");

                    b.Property<string>("ProcessId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("StartedAt");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Variables")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BusinessKey");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("State");

                    b.HasIndex("TenantId");

                    b.ToTable("ProcessInstances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ActiveTasks = "[]",
                            ActiveTokens = "[]",
                            BusinessKey = "BK-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstanceId = "sample-instance-1",
                            LastModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProcessDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProcessId = "SampleProcess",
                            StartedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "Running",
                            Status = 0,
                            Variables = "{}"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Roles")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            IsActive = true,
                            LastModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Roles = "[\"admin\"]",
                            Username = "admin"
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@example.com",
                            IsActive = true,
                            LastModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Roles = "[\"user\"]",
                            Username = "user1"
                        },
                        new
                        {
                            Id = "3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@example.com",
                            IsActive = true,
                            LastModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Roles = "[\"user\"]",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee");

                    b.Property<string>("CandidateRole")
                        .IsRequired();

                    b.PrimitiveCollection<string>("CandidateUsers")
                        .IsRequired();

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DueDate");

                    b.Property<string>("FormKey")
                        .HasMaxLength(255);

                    b.Property<string>("FormSchema");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("ModifiedBy")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("ProcessInstanceId");

                    b.PrimitiveCollection<string>("RequiredFields")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CandidateRole = "",
                            CandidateUsers = "[]",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            Name = "Review Request",
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RequiredFields = "[]",
                            Status = 0,
                            Type = "userTask"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<Guid>("ProcessInstanceId");

                    b.Property<Guid>("ScopeId");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("ScopeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.ToTable("Variables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "approvalRequired",
                            ProcessInstanceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ScopeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Type = "boolean",
                            Value = "true"
                        });
                });

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.CmmnHistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CaseFileJson")
                        .IsRequired();

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CompletedPlanItemsJson")
                        .IsRequired();

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "Timestamp");

                    b.ToTable("CmmnHistory");
                });

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.FeatureFlagRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<bool>("Enabled");

                    b.HasKey("Name");

                    b.ToTable("FeatureFlags");

                    b.HasData(
                        new
                        {
                            Name = "liveinspector",
                            Enabled = true
                        },
                        new
                        {
                            Name = "predictiveanalytics",
                            Enabled = false
                        },
                        new
                        {
                            Name = "processminingapi",
                            Enabled = false
                        });
                });

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.IdentityAuthorizationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128);

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "GroupId", "Resource")
                        .IsUnique();

                    b.ToTable("IdentityAuthorizations");
                });

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.IdentityGroupMembershipRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(128);

                    b.Property<string>("UserId")
                        .HasMaxLength(128);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityGroupMemberships");
                });

            modelBuilder.Entity("VertexBPMN.Infrastructure.Persistence.IdentityGroupRecord", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("IdentityGroups");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ExecutionToken", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", null)
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.HistoryEvent", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Incident", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Job", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.MultiInstanceExecution", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", null)
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessDefinition", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.EngineDeployment", "Deployment")
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessInstance", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.UserTask", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", null)
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Variable", b =>
                {
                    b.HasOne("VertexBPMN.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
