// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence.Services;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.ProcessMiningEvents
{
    [DbContext(typeof(ProcessMiningEventDbContext))]
    partial class ProcessMiningEventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("VertexBPMN.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128);

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8000);

                    b.Property<string>("Resource")
                        .HasMaxLength(300);

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200);

                    b.Property<int>("StatusCode");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.ProcessMiningEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActivityId")
                        .HasMaxLength(100);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(4000);

                    b.Property<string>("ProcessInstanceId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("TaskId")
                        .HasMaxLength(100);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = "startEvent1",
                            EventType = "PROCESS_STARTED",
                            ProcessInstanceId = "33333333-3333-3333-3333-333333333333",
                            TenantId = "tenant-default",
                            Timestamp = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "system"
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = "activity_userTask_1",
                            EventType = "TASK_CREATED",
                            PayloadJson = "{\"name\":\"Review Request\"}",
                            ProcessInstanceId = "33333333-3333-3333-3333-333333333333",
                            TaskId = "55555555-5555-5555-5555-555555555555",
                            TenantId = "tenant-default",
                            Timestamp = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 1, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
