// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence.Services;

#nullable disable

namespace VertexBPMN.Persistence.Migrations.ProcessMiningEvents
{
    [DbContext(typeof(ProcessMiningEventDbContext))]
    partial class ProcessMiningEventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VertexBPMN.Domain.Interfaces.ProcessMiningEvent", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("EventType").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("ProcessInstanceId").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("TaskId").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("ActivityId").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("UserId").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("Timestamp").HasColumnType("TEXT");
                b.Property<string>("PayloadJson").HasMaxLength(4000).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("EventType");
                b.HasIndex("ProcessInstanceId");
                b.HasIndex("TenantId");
                b.HasIndex("Timestamp");
                b.ToTable("Events");
            });
#pragma warning restore 612, 618
        }
    }
}
