// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Studio.Services;

#nullable disable

namespace VertexBPMN.Studio.Migrations.OidcSession
{
    [DbContext(typeof(OidcSessionStoreDbContext))]
    partial class OidcSessionStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("VertexBPMN.Studio.Services.OidcSessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64);

                    b.Property<DateTimeOffset>("ExpiresAtUtc");

                    b.Property<byte[]>("ProtectedPayload")
                        .IsRequired();

                    b.Property<long>("Revision");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTimeOffset>("UpdatedAtUtc");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("OidcSessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
