<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <StartupObject>VertexBPMN.Benchmarks.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VertexBPMN.Parsing\VertexBPMN.Parsing.csproj" />
    <ProjectReference Include="..\..\tests\VertexBPMN.Test.Parsing\VertexBPMN.Test.Parsing.csproj" />
  </ItemGroup>

</Project>