namespace VertexBPMN.EntityGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

[Generator]
public class EntityFromModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Syntax-Provider: finde Klassen
        var classSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, ct) =>
                    node is ClassDeclarationSyntax cds
                    && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword))
                    && cds.Parent is NamespaceDeclarationSyntax,
                transform: (ctx, ct) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var model = ctx.SemanticModel;
                    var typeSymbol = model.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
                    if (typeSymbol == null)
                        return null;

                    // Überprüfe: ist Klasse, nicht abstrakt, im gewünschten Namespace
                    if (typeSymbol.TypeKind != TypeKind.Class
                        || typeSymbol.IsAbstract)
                    {
                        return null;
                    }

                    // Beispiel: Namespace muss mit „YourApp.Domain.Models“ beginnen
                    var ns = typeSymbol.ContainingNamespace?.ToDisplayString();
                    if (ns == null || !ns.StartsWith("VertexBPMN.Domain.Model.Bpmn"))
                        return null;

                    return typeSymbol;
                })
            .Where(sym => sym != null)
            .Select<INamedTypeSymbol, INamedTypeSymbol>((sym, ct) => sym!);

        // 2. Generierung
        context.RegisterSourceOutput(classSymbols, (spc, typeSymbol) =>
        {
            var symbol = typeSymbol;
            var originalNs = symbol.ContainingNamespace.ToDisplayString();
            var entityNs = originalNs + ".Entities";
            var className = symbol.Name;
            var entityName = className + "Entity";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"namespace {entityNs}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {entityName}");
            sb.AppendLine("    {");

            foreach (var prop in symbol.GetMembers().OfType<IPropertySymbol>())
            {
                if (prop.DeclaredAccessibility == Accessibility.Public && !prop.IsStatic)
                {
                    var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"        public {typeName} {prop.Name} {{ get; set; }}");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{entityName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}

