// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.Decision
{
    [DbContext(typeof(DecisionDbContext))]
    [Migration("20250919222005_InitDecisionStore")]
    partial class InitDecisionStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VertexBPMN.Domain.Entities.DecisionDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DmnXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("Key", "TenantId")
                        .IsUnique();

                    b.ToTable("DecisionDefinitions", (string)null);
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.DecisionInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionDefinitionKey");

                    b.HasIndex("EvaluationTime");

                    b.HasIndex("TenantId");

                    b.HasIndex("DecisionDefinitionKey", "TenantId");

                    b.ToTable("DecisionInstances", (string)null);
                });

            modelBuilder.Entity("VertexBPMN.Domain.Entities.Modeling.DmnDecisionTable", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HitPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outputs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Name");

                    b.ToTable("DmnDecisionTables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
