// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertexBPMN.Infrastructure.Persistence;

#nullable disable

namespace VertexBPMN.Infrastructure.Persistence.Migrations.Decision
{
    [DbContext(typeof(DecisionDbContext))]
    [Migration("20260809131159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("VertexBPMN.Domain.Model.Dmn.DecisionDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200);

                    b.Property<string>("DmnXml")
                        .IsRequired();

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("Key", "TenantId")
                        .IsUnique();

                    b.ToTable("DecisionDefinitions", (string)null);
                });

            modelBuilder.Entity("VertexBPMN.Domain.Model.Dmn.DecisionInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<string>("DecisionDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EvaluationTime");

                    b.Property<bool>("Failed");

                    b.Property<string>("InputVariables")
                        .IsRequired();

                    b.Property<string>("OutputVariables")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("DecisionDefinitionKey");

                    b.HasIndex("EvaluationTime");

                    b.HasIndex("TenantId");

                    b.HasIndex("DecisionDefinitionKey", "TenantId");

                    b.ToTable("DecisionInstances", (string)null);
                });

            modelBuilder.Entity("VertexBPMN.Domain.Model.Dmn.DmnDecisionTable", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200);

                    b.Property<string>("HitPolicy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Inputs")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.Property<string>("Outputs")
                        .IsRequired();

                    b.Property<string>("Rules")
                        .IsRequired();

                    b.HasKey("Key");

                    b.HasIndex("Name");

                    b.ToTable("DmnDecisionTables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
