<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Parsing\BpmnParser1.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VertexBPMN.Domain\VertexBPMN.Domain.csproj" />
    <ProjectReference Include="..\VertexBPMN.Application\VertexBPMN.Application.csproj" />
    <ProjectReference Include="..\VertexBPMN.Infrastructure\VertexBPMN.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
