<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
	<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
	<OutputType>Exe</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  <!--<ProjectReference Include="..\VertexBPMN.McpAdapter\VertexBPMN.McpAdapter.csproj" />-->
  </ItemGroup>
<ItemGroup>
    <None Include="TestData\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
<ItemGroup>
  <Compile Remove="Grpc\**" />
  <EmbeddedResource Remove="Grpc\**" />
  <None Remove="Grpc\**" />
</ItemGroup>
<ItemGroup>
  <Content Include="appsettings.Test.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
  </Content>
</ItemGroup>
<ItemGroup>
<None Update="TestData\agents.js">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
<None Update="TestData\dinnerDecisions.dmn">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
<None Update="TestData\ExampleProcess.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
<None Update="TestData\ExternalTask1.bpmn">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
<None Update="TestData\hello-world.bpmn">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
  <None Update="TestData\Reference\A.1.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\A.2.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\A.2.1.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\A.3.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\A.4.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\A.4.1.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\B.1.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\B.2.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.1.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.1.1.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.2.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.3.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.4.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.5.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.6.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.7.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.8.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.8.1.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.9.0.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.9.1.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\C.9.2.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Reference\xsdTypes.xsd">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\SemanticKernelTestProcess.bpmn">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="TestData\Sqlite.sql">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
<ItemGroup>
  <Folder Include="Integration\Services\" />
</ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\..\src\VertexBPMN.Cli\VertexBPMN.Cli.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Api\VertexBPMN.Api.csproj" Aliases="global,api" />
  <ProjectReference Include="..\..\src\VertexBPMN.Application\VertexBPMN.Application.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Domain\VertexBPMN.Domain.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Engine\VertexBPMN.Engine.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Infrastructure\VertexBPMN.Infrastructure.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Integration\McpAdapter\VertexBPMN.McpAdapter.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Integration\McpAgentPlugin\VertexBPMN.McpAgentPlugin.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Integration\McpClient\VertexBPMN.McpClient.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Studio\VertexBPMN.Studio.csproj" />
  <ProjectReference Include="..\..\src\VertexBPMN.Sdk\VertexBPMN.Sdk.csproj" />
</ItemGroup>

</Project>
