name: VertexBPMN CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore VertexBPMN.sln
    - name: Build
      run: dotnet build VertexBPMN.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test VertexBPMN.Tests/VertexBPMN.Tests.csproj --no-build --verbosity normal
    - name: Publish Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: vertexbpmn:ci
